# serverless.yml 

service: coms-backend-api

custom:
  # ensure the file `secrets.json` exists
  # at the root of the project. Do not commit this file.
  # Ensure the values referenced below are defined.
  secrets: ${file(secrets.json)}


provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.secrets.NODE_ENV}
  region: us-west-2
  environment:
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    SENDER_EMAIL: ${self:custom.secrets.SENDER_EMAIL}
    DEST_EMAIL: ${self:custom.secrets.DEST_EMAIL}
    DOMAIN: ${self:custom.secrets.DOMAIN}
    STRIPE_SECRET_KEY: ${self:custom.secrets.STRIPE_SECRET_KEY}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: "*"



functions:
  send:
    handler: contact.send
    events:
      - http:
          path: email/send
          method: post
          cors: true

  # Append other functions here
